DROP DATABASE IF EXISTS `stcal`;
CREATE DATABASE IF NOT EXISTS `stcal` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE `stcal`;

DROP TABLE IF EXISTS `test`;
CREATE TABLE IF NOT EXISTS `test` (
  `id_test` int(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id_test`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=2 ;

INSERT INTO `test` (`id_test`) VALUES (NULL);